import CoreGraphics
import Foundation
import MLX
import XCTest

@testable import MLXDA3Streaming

/// End-to-end parity test for SALAD loop detection.
///
/// Compares Swift `LoopDetector` output (descriptors + loop pairs) against a
/// python `loop_utils.LoopDetector` fixture generated by
/// `Scripts/generate_loop_detection_fixture.py`.
///
/// Tolerances are loose because:
/// - PIL bilinear resize vs `CGContext` bicubic produce different pixel
///   inputs to the model (~1 LSB on most pixels, larger on high-frequency
///   regions).
/// - 12 transformer layers + Sinkhorn iterations compound the fp32 matmul
///   reduction-order noise documented for DA3.
/// - L2-normalised descriptors hide the absolute magnitude of drift; we
///   compare the cosine similarity of swift-vs-python *descriptors* per
///   frame (which should be close to 1 if the port is correct) rather than
///   raw element diff.
final class LoopDetectionFixtureTests: XCTestCase {
    func testSaladLoopDetectionParity() throws {
        let env = ProcessInfo.processInfo.environment
        let packageRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let defaultFixtureDir = packageRoot.appendingPathComponent("Tests/Fixtures").path
        let fixtureDir = env["DA3_LOOP_FIXTURE_DIR"] ?? defaultFixtureDir
        let imageDir = env["DA3_LOOP_FIXTURE_IMAGES"]
            ?? packageRoot.appendingPathComponent("tmp/da3_frames").path
        let weightsPath = env["DA3_SALAD_WEIGHTS"] ?? ""

        let fixtureURL = URL(fileURLWithPath: fixtureDir)
            .appendingPathComponent("salad_loop_fixture.safetensors")

        guard FileManager.default.fileExists(atPath: fixtureURL.path),
              FileManager.default.fileExists(atPath: weightsPath),
              FileManager.default.fileExists(atPath: imageDir)
        else {
            throw XCTSkip("SALAD loop fixture, weights, or input frames not found. Generate via Scripts/generate_loop_detection_fixture.py and convert ckpt → safetensors via Scripts/convert_salad_to_safetensors.py.")
        }

        let fixture = try loadArrays(url: fixtureURL)
        guard let pyDesc = fixture["descriptors"],
              let pyPairs = fixture["loop_pairs"]
        else {
            XCTFail("Fixture missing keys")
            return
        }

        var cfg = LoopDetector.Config()
        cfg.imageSize = (height: 336, width: 336)
        cfg.batchSize = 8
        cfg.similarityThreshold = 0.5
        cfg.topK = 3
        cfg.minFrameDistance = 1
        cfg.useNMS = false
        cfg.nmsThreshold = 25

        let detector = try LoopDetector.fromPretrained(weightsPath, config: cfg, dtype: .float32)
        let imagePaths = try ImageDirectory.listImagePaths(in: imageDir).prefix(8)
        let images: [CGImage] = try imagePaths.map { try ImageDirectory.loadCGImage(path: $0) }
        let (swDesc, swLoops) = detector.detect(images: images)

        // 1) Descriptor cosine similarity per frame: should be very close to 1.
        XCTAssertEqual(swDesc.shape, pyDesc.shape, "descriptor shape mismatch")
        try assertCosineMatch(actual: swDesc, expected: pyDesc, perFrameMin: 0.985)

        // 2) Pair set overlap. Swift and python may reorder ties slightly, so
        // compare as sets of (lo, hi) pairs and require ≥60% Jaccard overlap.
        var swSet = Set<Tuple>()
        for l in swLoops { swSet.insert(Tuple(min(l.a, l.b), max(l.a, l.b))) }
        let pyArr = pyPairs.asArray(Float.self)
        var pySet = Set<Tuple>()
        let nPairs = pyPairs.dim(0)
        for i in 0..<nPairs {
            let a = Int(pyArr[i * 3 + 0])
            let b = Int(pyArr[i * 3 + 1])
            pySet.insert(Tuple(min(a, b), max(a, b)))
        }
        let intersection = swSet.intersection(pySet).count
        let union = swSet.union(pySet).count
        let jaccard = union == 0 ? 1.0 : Float(intersection) / Float(union)
        XCTAssertGreaterThanOrEqual(
            jaccard, 0.6,
            "pair set Jaccard overlap too low: sw=\(swSet.count), py=\(pySet.count), inter=\(intersection)"
        )
    }

    private struct Tuple: Hashable {
        let a: Int
        let b: Int
        init(_ a: Int, _ b: Int) { self.a = a; self.b = b }
    }

    /// Per-frame cosine similarity of descriptor vectors. Each pair should be
    /// near 1.0 (descriptors are L2-normalised so cosine = inner product).
    private func assertCosineMatch(
        actual: MLXArray, expected: MLXArray, perFrameMin: Float,
        file: StaticString = #filePath, line: UInt = #line
    ) throws {
        let af = actual.asType(.float32)
        let ef = expected.asType(.float32)
        eval(af, ef)
        let a = af.asArray(Float.self)
        let e = ef.asArray(Float.self)
        let n = af.dim(0)
        let d = af.dim(1)
        var minCos: Float = 1.0
        var avgCos: Float = 0
        for i in 0..<n {
            var dot: Float = 0
            for k in 0..<d {
                dot += a[i * d + k] * e[i * d + k]
            }
            // Both already L2-normalised; cosine sim = dot product.
            minCos = min(minCos, dot)
            avgCos += dot
        }
        avgCos /= Float(n)
        if minCos < perFrameMin {
            XCTFail("per-frame descriptor cosine too low: min=\(minCos) avg=\(avgCos) (threshold=\(perFrameMin))",
                    file: file, line: line)
        }
    }
}
